### ISSUE TITLE
Add custom tokens to support Unreal Engine C++ Variables

### ISSUE THREAD

**Issue by Ares9323** [Benio101/Color.Token#12]
# Feature request: Leave the possibility to the user to add custom tokens
#### Pros
-More customization
-Matching UE Standard colors
-Could be applied to specific struct variables

#### Cons
- None

### Relevance
- Potentially relevant to all the Unreal Engine C++ users, but not limited to them

## Additional informations
-Example of the most common variables:

FText -> #F6AAFF
FString -> #EF00C8
FVector -> #E3B31D
FVector2D -> #0158CA
FTransform -> #F26D00
FRotator -> #8D9EE0
int8 -> #005F57
int32 -> #1AD09F
float -> #8BDD3B
bool -> #FF0000

(It would be really great to use hex values instead of the default old RGB picker that doesn't support them)

P.S. I forked your repo and tried to add the values copying your syntax, but it looks like it doesn't work. In case you want to give it a try [here's the commit](https://github.com/Ares9323/Color.Token/commit/e8b6e8458bd57b59b1a0f573f2c4da6f7f514ef1)

**Comment by Benio101** [comment]
If I remember correctly, UE _variables_ like `FVector` or `int8` are xeither direct macros provided by included UE header xor macros generated by UHT, which does not parse the source code correctly and used to break on simple changes like reordering keywords of function declaration. Did you try it with the option `Color macros` enabled?

**Comment by Benio101** [comment]
I've changed basic definition of UE tokens from keyword to macros and changed their default color to be consistient with existing C++ ones. Now it should work, and I've added support for token you've listed. If you wish to add more UE tokens, feel free to reopen this issue or open a new one.

If you wish to add a feature to add custom tokens, PR is welcome, however it's unlikely that I shall implement it in near future.
