### ISSUE TITLE
Enable for 'C'?

### ISSUE THREAD

**Issue by davegi** [Benio101/Color.Token#2]
An chance this can be enabled for `.c` files? Specifically, when using `<stdbool.h>`, the type `bool` is colorized differently if the file extension is `.c` vs. `.cpp`.
Doesn't seem to colorize `bool` when used in a `.h` file either.

**Comment by Benio101** [comment]
Extension works with all files of [`[ContentType("C/C++")]`](https://github.com/Benio101/Color.Token/blob/03e06f19e8e88eb2075708842803c7d92981f573/Color.Token/Provider.cs#L10), as stated in [¶Description](https://github.com/Benio101/Color.Token#description). Especially, it works with `.h` and `.c` files as they are classified as `C/C++` by default.

The reason why `bool` is not colorized in your case is different. Actually, [`stdbool.h`](https://en.cppreference.com/w/c/types/boolean) defines `bool` as macro, so it's classified as macro, not as keyword and thus, is not subject of `Color.Token` extension as it affects listed keywords and specifiers with special meanings only, as stated in [¶List of Tokens](https://github.com/Benio101/Color.Token#list-of-tokens).

I'll add an option to colorize macros which text is exact as supported tokens.

**Comment by davegi** [comment]
Thanks. 
I saw the content type but was then thrown by `bool` and the fact that even though the Description does mention `C/C++`, it then mentions "...eg .cpp or .h files."  When changing the extension from .cpp to .c, and observing the different display of `bool`...
Well, I'm thrilled that it works for 'C' and will grab the macro enabled version when it's available.

**Comment by davegi** [comment]
Sorry. Didn't mean to close!!!

**Comment by Benio101** [comment]
Sorry for late push, was moving to a new house and participating in weekend event, thus had no free time. Hopefully resolved the issue by adding described option (Color macros, disabled by default).

In order to enable new option, head to Tools → Options → Color.Token → Color macros and change `False` to `True`. Option's change should be permanent and is managed internally by Visual Studio.
