### ISSUE TITLE
Missing Microsoft.VisualStudio.Threading

### ISSUE THREAD

**Issue by dmateja** [Benio101/Color.Token#3]
Hi

ActivityLog:
SetSite failed for package [Package]Source: 'Color.Token' Description: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=16.0.0.0,
--

The same problem for Color.Comment

Visual Studio 2017 Professional 15.9.13

**Comment by Benio101** [comment]
Fixed in [`1.3.1+2017`](https://github.com/Benio101/Color.Token/releases/tag/1.3.1%2B2017). Live on marketplace too.
Sorry, didn't knew that nugets `16.*` won't be pulled on VS2017. I've learned it now.
